from typing import Dict, Any


SCENARIO_METADATA: Dict[str, Dict[str, Any]] = {
    "NORMAL": {
        "name": "Normal Operations Baseline",
        "description": "Balanced passenger timetables, standard freight density, routine maintenance backlog across Civil, S&T, and TRD.",
        "purpose": "Provides baseline operational metrics for standard block planning.",
        "traffic_density": "NORMAL",
        "maintenance_demand": "MODERATE",
        "resource_availability": "ADEQUATE",
        "train_count": 35,
        "task_count": 35,
        "resource_count": 18,
        "overdue_ratio": 0.10,
        "emergency_count": 0,
        "multi_dept_overlap_target": 2,
        "overrun_scenario": False,
    },
    "HEAVY_TRAFFIC": {
        "name": "Heavy Traffic Density",
        "description": "High-density corridor traffic with tight passenger train headways and frequent freight movements, yielding narrow access windows (20-40 mins).",
        "purpose": "Tests line access discovery and schedule fitting under extreme traffic pressure.",
        "traffic_density": "HIGH",
        "maintenance_demand": "MODERATE",
        "resource_availability": "ADEQUATE",
        "train_count": 58,
        "task_count": 35,
        "resource_count": 18,
        "overdue_ratio": 0.15,
        "emergency_count": 0,
        "multi_dept_overlap_target": 3,
        "overrun_scenario": False,
    },
    "HIGH_MAINTENANCE_DEMAND": {
        "name": "High Maintenance Demand",
        "description": "Surge of 65+ work order requests including multiple overdue items and degraded asset condition scores competing for corridor access.",
        "purpose": "Tests multi-attribute task prioritization, safety urgency scoring, and deferral logic.",
        "traffic_density": "NORMAL",
        "maintenance_demand": "HIGH",
        "resource_availability": "ADEQUATE",
        "train_count": 35,
        "task_count": 68,
        "resource_count": 22,
        "overdue_ratio": 0.35,
        "emergency_count": 0,
        "multi_dept_overlap_target": 5,
        "overrun_scenario": False,
    },
    "RESOURCE_SHORTAGE": {
        "name": "Resource Shortage Contention",
        "description": "Constrained resource pool (e.g. only 1 track tamping machine and 1 tower car for entire corridor), creating severe machine routing bottlenecks.",
        "purpose": "Tests resource-constrained scheduling and machine routing feasibility.",
        "traffic_density": "NORMAL",
        "maintenance_demand": "MODERATE",
        "resource_availability": "CONSTRAINED",
        "train_count": 35,
        "task_count": 45,
        "resource_count": 8,  # Intentionally limited
        "overdue_ratio": 0.15,
        "emergency_count": 0,
        "multi_dept_overlap_target": 4,
        "overrun_scenario": False,
    },
    "MULTI_DEPARTMENT_OVERLAP": {
        "name": "Multi-Department Overlapping Demands",
        "description": "Key SIH26027 scenario: Civil (ENGG), Signal & Telecom (S&T), and Electrical (TRD) independently request blocks on the exact same section and time window.",
        "purpose": "Evaluates compatible maintenance-task bundling logic to merge cross-departmental requests.",
        "traffic_density": "NORMAL",
        "maintenance_demand": "HIGH_CO-LOCATION",
        "resource_availability": "ADEQUATE",
        "train_count": 38,
        "task_count": 48,
        "resource_count": 20,
        "overdue_ratio": 0.20,
        "emergency_count": 0,
        "multi_dept_overlap_target": 8,  # Multiple forced overlapping clusters
        "overrun_scenario": False,
    },
    "MAINTENANCE_OVERRUN": {
        "name": "Maintenance Overrun Disruption",
        "description": "Baseline plan environment with pre-existing execution records displaying 35-minute duration overruns due to equipment breakdown.",
        "purpose": "Tests execution tracking and dynamic schedule repair after overruns.",
        "traffic_density": "NORMAL",
        "maintenance_demand": "MODERATE",
        "resource_availability": "ADEQUATE",
        "train_count": 35,
        "task_count": 35,
        "resource_count": 18,
        "overdue_ratio": 0.10,
        "emergency_count": 0,
        "multi_dept_overlap_target": 2,
        "overrun_scenario": True,
    },
    "EMERGENCY_MAINTENANCE": {
        "name": "Emergency Unscheduled Defect",
        "description": "Unscheduled critical main-line track defect (Priority 9.8/10) detected during peak morning hours requiring immediate line closure.",
        "purpose": "Tests real-time preemption, emergency task insertion, and schedule disruption handling.",
        "traffic_density": "HIGH",
        "maintenance_demand": "MODERATE",
        "resource_availability": "ADEQUATE",
        "train_count": 42,
        "task_count": 40,
        "resource_count": 18,
        "overdue_ratio": 0.15,
        "emergency_count": 2,  # Emergency high-priority work orders
        "multi_dept_overlap_target": 3,
        "overrun_scenario": False,
    },
    "COMBINED_STRESS_TEST": {
        "name": "Combined Operational Stress Test",
        "description": "Comprehensive demonstration scenario combining heavy traffic density, 60+ work orders, multi-department co-location, resource scarcity, and emergency repairs.",
        "purpose": "Ultimate system stress test to evaluate full architecture resilience, explainability, and dynamic replanning.",
        "traffic_density": "HIGH",
        "maintenance_demand": "HIGH",
        "resource_availability": "CONSTRAINED",
        "train_count": 55,
        "task_count": 65,
        "resource_count": 10,
        "overdue_ratio": 0.30,
        "emergency_count": 2,
        "multi_dept_overlap_target": 9,
        "overrun_scenario": True,
    },
}
